query Category($categoryId: Int!) {
  bigcommerce(entityId: $categoryId) {
    category(entityId: $categoryId) {
      name
      description
      entityId
      products {
        edges {
          node {
            name
            defaultImage {
              urlOriginal
            }
            brand {
              name
            }
            plainTextDescription
            sku
            id
            entityId
            prices {
              price {
                value
                currencyCode
              }
            }
          }
        }
      }
    }
  }
}
