query Page($slug: String!, $stage: Stage! = PUBLISHED) {
  page(where: { slug: $slug }, stage: $stage) {
    __typename
    id
    slug
    title
    description
    image
    components {
      ... on Editorial {
        id
        __typename
        image
        components {
          ... on Card {
            id
            __typename
            cta
            image
            title
            url
          }
          ... on Cta {
            id
            __typename
            chapeau
            cta
            description
            title
            url
          }
        }
      }
      ... on Hero {
        id
        __typename
        description
        image
        title
      }
      ... on ProductHighlight {
        id
        __typename
        productFocus {
          id
          __typename
          cta
          description
          image
          productId
          title
          url
          product {
            description
            id
            images {
              alt
              url
            }
            ingredients
            price
            name
            shortDescription
            slug
            stock
          }
        }
      }
      ... on Routine {
        id
        __typename
        chapeau
        cta
        description
        image
        title
        url
      }
    }
  }
}
