query Page($slug: String!) {
  page(where: { slug: $slug }) {
    slug
    title
    description
    image
    components {
      ... on Editorial {
        id
        __typename
        image
        components {
          ... on Card {
            id
            __typename
            cta
            image
            title
            url
          }
          ... on Cta {
            id
            __typename
            chapeau
            cta
            description
            title
            url
          }
        }
      }
      ... on Hero {
        id
        __typename
        description
        image
        title
      }
      ... on ProductHighlight {
        id
        __typename
        description
        cta
        image
        product
        theme
        title
        url
        variant
      }
      ... on Routine {
        id
        __typename
        chapeau
        cta
        description
        image
        title
        url
      }
    }
  }
}
